name: Actions Worflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Simple JS Actions
        id: greet
        uses: edgartec97/github-actions-test@v1
        with:
          who-to-greet: Jhon
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"
