name: Context

on: [push, pull_request]

jobs:
  functions:
    runs-on: ubuntu-20.04
    steps:
      - name: dump
        run: |
          echo ${{ contains(  'hello','55') }} 
          echo ${{ startsWith('hello','he') }} 
          echo ${{ endsWith(  'hello','lo') }} 
          echo ${{ format(    'hello {0} {1} {2}','World','!','!') }}
  context:
    runs-on: ubuntu-20.04
    if: github.event_name == 'push'
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: eccho "$GITHUB_CONTEXT"
      - name: Dump job context
        if: failure()
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        if: always()
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "$MATRIX_CONTEXT"
