name: Container

on: push

jobs:
  docker-steps:
    runs-on: ubuntu-20.04
    container:
      image: node:lts-alpine
    steps:
      - name: Log node version
        run: node -v
      - name: Step with docker
        uses: docker://node:14-alpine3.14
        with:
          entrypoint: "/bin/echo"
          args: '["Hello World"]'
      - name: Step with docker Log node version
        uses: docker://node:14-alpine3.14
        with:
          entrypoint: "/usr/local/bin/node"
          args: -v
      - uses: actions/checkout@v1
      - name: Run a script
        uses: docker://node:14-alpine3.14
        with:
          entrypoint: ./script.sh
          args: "Some string"
      - name: Send message by Slack
        uses: docker://technosophos/slack-notify
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: "Hello From GitHub Actions"
  node-docker:
    runs-on: ubuntu-20.04
    services:
      app:
        image: edgarcv99/simple-docker-nodejs-app:0.0.1
        ports:
          - 3000:3000
      mongodb:
        image: mongo
        ports:
          - 27017:27017
    steps:
      - name: Post a user
        run: |
          curl -X POST http://localhost:3000/api/user -H 'Content-Type: application/json'  -d  '{"username": "Edgar Vega", "address": "Framboyanes" }'
      - name: Get Users
        run: curl http://localhost:3000/api/users
