name: Container

on: push

jobs:
  node-docker:
    runs-on: ubuntu-20.04
    container: node:lts
    steps:
      - name: Log node version
        run: |
          node -v
          cat /etc/os-release
