name: Container

on: push

jobs:
  node-docker:
    runs-on: ubuntu-20.04
    services:
      app:
        image: edgarcv99/simple-docker-nodejs-app:0.0.1
        ports:
          - 3000:3000
      mongo:
        image: mongo
        ports:
          - 27017:27017
    steps:
      - name: Post a user
        run: |
          curl -X POST http://localhost:3001/api/user -H 'Content-Type: application/json'  -d  '{"username": "Edgar Vega", "address": "Framboyanes" }'
      - name: Get Users
        run: curl http://localhost:3000/api/users
