name: Matrix

on: push

jobs:
  node-version:
    runs-on: ubuntu-20.04
    steps:
      - name: Log node version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: 6
      - name: Log node version 2
        run: node -v
